---

- name: OS-specific pre-installation tasks
  include_tasks: "{{ preinstall_tasks }}"
  vars:
    preinstall_tasks: "{{ lookup('first_found', lookup_params) }}"
    lookup_params:
      files:
        - "{{ role_path }}/tasks/podman/preinstall/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ role_path }}/tasks/podman/preinstall/{{ ansible_distribution }}.yml"
        - "{{ role_path }}/tasks/podman/preinstall/{{ ansible_os_family }}.yml"
      # If none of those exist for the current OS, that is fine
      skip: true
  when: preinstall_tasks

- name: Install podman packages
  package:
    name: "{{ podman_packages }}"
    state: latest

- name: Install script for attaching to pod infra containers
  copy:
    src: podman/podman-pod-infra-attach.sh
    dest: /usr/bin/
    mode: +x

- name: Create podman user
  user:
    name: podman
    home: /var/lib/podman
