---

- name: "Install systemd unit for {{ podman_service_name }}"
  template:
    src: podman/systemd.{{ podman_service_type }}.service.j2
    dest: /etc/systemd/system/{{ podman_service_name }}.service
