---

# Include the variables for the OS distribution we are running on
# Note that we don't use first_found across the whole list of files because
# we want to include all the ones that apply, in the order in which they are defined
# However we do use first_found to handle the case where the file doesn't exist at all
- name: Include OS-specific variables
  include_vars: "{{ vars_file }}"
  vars:
    vars_file: "{{ lookup('first_found', lookup_params) }}"
    lookup_params:
      files: ["{{ item }}"]
      skip: true
  when: vars_file
  loop:
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure up-to-date CA certificates
  package:
    name: ca-certificates
    state: latest

# Required for become to an unprivileged user to work
# Using the apt module seems to work more reliably than package :-/
- name: Install ACL package
  apt:
    update_cache: yes
    name: acl
    state: present
  when: ansible_os_family == "Debian"

- block:
    - include_tasks: desktop.yml
    - include_tasks: vnc_server.yml
  when: desktop_enabled is defined and desktop_enabled

- include_role:
    name: linux-ansible-init

- include_role: 
    name: linux-podman
    tasks_from: install.yml

- include_role:
    name: linux-data-volumes
  vars:
    data_volumes:
      - metadata_var: zenith_volume_id
        mountpoint: /etc/zenith/ssh
        opts: "defaults,nofail"
        owner: podman
        group: podman
      - metadata_var: data_volume_id
        mountpoint: /data
        opts: "defaults,nofail"
        owner: ubuntu
        group: ubuntu

- include_tasks: guacamole.yml

- import_role:
    name: linux-zenith-client
  vars:
    zenith_client_name: guacamole-zenith-client
    zenith_client_pod: guacamole
    zenith_client_wants: [guacamole-mitm]
    zenith_forward_to_port: 8081

- name: Run cloud-init cleanup
  command: cloud-init clean --logs --seed
