---

#####
## These tasks install TigerVNC server and perform global configuration
#####

- name: Install VNC server
  package:
    name: "{{ tigervnc_server_packages }}"
    state: present

# CentOS includes a systemd unit, Ubuntu does not
- name: Install vncserver systemd unit file
  copy:
    src: vnc_server/vncserver@.service
    dest: /etc/systemd/system/
  when: ansible_distribution == 'Ubuntu'

- name: Ensure systemd override directory exists
  file:
    path: /etc/systemd/system/vncserver@.service.d
    state: directory

- name: Install systemd overrides
  copy:
    src: "vnc_server/{{ item }}"
    dest: /etc/systemd/system/vncserver@.service.d/
  loop:
    - start_order.conf
    - restart.conf

- name: Get guacamole user info
  user:
    name: "{{ guacamole_user }}"
    state: present
  register: guacamole_user_info

- name: Set VNC server user facts for guacamole user
  set_fact:
    guacamole_user_vnc_config_dir: "{{ guacamole_user_info.home }}/.vnc"

- name: Ensure systemd overrides directory exists
  file:
    path: /etc/systemd/system/vncserver@:1.service.d
    state: directory

- name: Configure user for systemd unit
  copy:
    dest: /etc/systemd/system/vncserver@:1.service.d/user.conf
    content: |
      [Service]
      Environment=VNCSERVER_PASSWD_FILE={{ guacamole_user_vnc_config_dir }}/passwd
      User={{ guacamole_user }}
