---

- name: Ensure Zenith config directory exists
  file:
    path: /etc/zenith/{{ zenith_client_name }}
    state: directory

- name: Create podman volume to persist SSH key
  containers.podman.podman_volume:
    name: "{{ zenith_client_name }}-ssh"
  become: yes
  become_user: "{{ podman_service_user }}"

- name: Pull image for Zenith client
  containers.podman.podman_image:
    name: "{{ zenith_client_image }}"
  become: yes
  become_user: "{{ podman_service_user }}"

- name: Install systemd unit for Zenith client
  include_tasks: podman/systemd-unit.yml
  vars:
    podman_service_name: "{{ zenith_client_name }}"
    podman_service_type: container
    podman_service_pod: "{{ zenith_client_pod }}"
    podman_service_wants: "{{ zenith_client_wants }}"
    podman_service_image: "{{ zenith_client_image }}"
    podman_service_command: "zenith-client connect"
    podman_service_volumes:
      - /etc/zenith/{{ zenith_client_name }}:/etc/zenith:ro
      - "{{ zenith_client_name }}-ssh:/home/zenith/.ssh:ro"
