---

desktop_environment_package: ubuntu-desktop-minimal

tigervnc_server_packages: [tigervnc-standalone-server, tigervnc-xorg-extension]

podman_packages: [podman-rootless, containernetworking-plugins]
