name: Build images
on:
  push:
    branches: [main]
jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Each job consumes a FIP, so limit the number that can run concurrently
      max-parallel: 1
      matrix:
        include:
          - name: ubuntu-desktop
            template: linux-desktop
            var-files: common,kvm,linux,ubuntu
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/base/common.env
                - env/${{ secrets.ENVIRONMENT }}/common.env
                - env/base/kvm.env
                - env/${{ secrets.ENVIRONMENT }}/kvm.env
                - env/base/linux.env
                - env/${{ secrets.ENVIRONMENT }}/linux.env
                - env/base/ubuntu.env
                - env/${{ secrets.ENVIRONMENT }}/ubuntu.env
                - vars/base/common.json
                - vars/${{ secrets.ENVIRONMENT }}/common.json
                - vars/base/kvm.json
                - vars/${{ secrets.ENVIRONMENT }}/kvm.json
                - vars/base/linux.json
                - vars/${{ secrets.ENVIRONMENT }}/linux.json
                - vars/base/ubuntu.json
                - vars/${{ secrets.ENVIRONMENT }}/ubuntu.json
                - packer/linux-desktop.pkr.hcl
                - ansible/linux-webconsole.yml
                - ansible/roles/linux-webconsole/**
                - ansible/roles/linux-ansible-init/**
                - ansible/roles/linux-podman/**
                - ansible/roles/linux-data-volumes/**
                - ansible/roles/linux-guacamole/**
                - ansible/roles/linux-monitoring/**
                - ansible/roles/linux-zenith-client/**
          - name: ubuntu-rdp-gateway
            template: linux-rdp-gateway
            var-files: common,kvm,linux,ubuntu
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/base/common.env
                - env/${{ secrets.ENVIRONMENT }}/common.env
                - env/base/kvm.env
                - env/${{ secrets.ENVIRONMENT }}/kvm.env
                - env/base/linux.env
                - env/${{ secrets.ENVIRONMENT }}/linux.env
                - env/base/ubuntu.env
                - env/${{ secrets.ENVIRONMENT }}/ubuntu.env
                - vars/base/common.json
                - vars/${{ secrets.ENVIRONMENT }}/common.json
                - vars/base/kvm.json
                - vars/${{ secrets.ENVIRONMENT }}/kvm.json
                - vars/base/linux.json
                - vars/${{ secrets.ENVIRONMENT }}/linux.json
                - vars/base/ubuntu.json
                - vars/${{ secrets.ENVIRONMENT }}/ubuntu.json
                - packer/linux-rdp-gateway.pkr.hcl
                - ansible/linux-rdp-gateway.yml
                - ansible/roles/linux-rdp-gateway/**
                - ansible/roles/linux-ansible-init/**
                - ansible/roles/linux-podman/**
                - ansible/roles/linux-data-volumes/**
                - ansible/roles/linux-guacamole/**
                - ansible/roles/linux-zenith-client/**
          - name: jupyter-repo2docker
            template: jupyter-repo2docker
            var-files: common,kvm,linux,ubuntu
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/base/common.env
                - env/${{ secrets.ENVIRONMENT }}/common.env
                - env/base/kvm.env
                - env/${{ secrets.ENVIRONMENT }}/kvm.env
                - env/base/linux.env
                - env/${{ secrets.ENVIRONMENT }}/linux.env
                - env/base/ubuntu.env
                - env/${{ secrets.ENVIRONMENT }}/ubuntu.env
                - vars/base/common.json
                - vars/${{ secrets.ENVIRONMENT }}/common.json
                - vars/base/kvm.json
                - vars/${{ secrets.ENVIRONMENT }}/kvm.json
                - vars/base/linux.json
                - vars/${{ secrets.ENVIRONMENT }}/linux.json
                - vars/base/ubuntu.json
                - vars/${{ secrets.ENVIRONMENT }}/ubuntu.json
                - packer/jupyter-repo2docker.pkr.hcl
                - ansible/jupyter-repo2docker.yml
                - ansible/roles/jupyter-repo2docker/**
                - ansible/roles/linux-ansible-init/**
                - ansible/roles/linux-podman/**
                - ansible/roles/linux-data-volumes/**
                - ansible/roles/linux-monitoring/**
                - ansible/roles/linux-zenith-client/**
          - name: kubernetes-1-23
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_23
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/base/common.env
                - env/${{ secrets.ENVIRONMENT }}/common.env
                - env/base/kvm.env
                - env/${{ secrets.ENVIRONMENT }}/kvm.env
                - env/base/linux.env
                - env/${{ secrets.ENVIRONMENT }}/linux.env
                - env/base/ubuntu.env
                - env/${{ secrets.ENVIRONMENT }}/ubuntu.env
                - env/base/kubernetes.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes.env
                - env/base/kubernetes_1_23.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes_1_23.env
                - vars/base/common.json
                - vars/${{ secrets.ENVIRONMENT }}/common.json
                - vars/base/kvm.json
                - vars/${{ secrets.ENVIRONMENT }}/kvm.json
                - vars/base/linux.json
                - vars/${{ secrets.ENVIRONMENT }}/linux.json
                - vars/base/ubuntu.json
                - vars/${{ secrets.ENVIRONMENT }}/ubuntu.json
                - vars/base/kubernetes.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes.json
                - vars/base/kubernetes_1_23.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes_1_23.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
          - name: kubernetes-1-24
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_24
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/base/common.env
                - env/${{ secrets.ENVIRONMENT }}/common.env
                - env/base/kvm.env
                - env/${{ secrets.ENVIRONMENT }}/kvm.env
                - env/base/linux.env
                - env/${{ secrets.ENVIRONMENT }}/linux.env
                - env/base/ubuntu.env
                - env/${{ secrets.ENVIRONMENT }}/ubuntu.env
                - env/base/kubernetes.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes.env
                - env/base/kubernetes_1_24.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes_1_24.env
                - vars/base/common.json
                - vars/${{ secrets.ENVIRONMENT }}/common.json
                - vars/base/kvm.json
                - vars/${{ secrets.ENVIRONMENT }}/kvm.json
                - vars/base/linux.json
                - vars/${{ secrets.ENVIRONMENT }}/linux.json
                - vars/base/ubuntu.json
                - vars/${{ secrets.ENVIRONMENT }}/ubuntu.json
                - vars/base/kubernetes.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes.json
                - vars/base/kubernetes_1_24.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes_1_24.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
          - name: kubernetes-1-25
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_25
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/base/common.env
                - env/${{ secrets.ENVIRONMENT }}/common.env
                - env/base/kvm.env
                - env/${{ secrets.ENVIRONMENT }}/kvm.env
                - env/base/linux.env
                - env/${{ secrets.ENVIRONMENT }}/linux.env
                - env/base/ubuntu.env
                - env/${{ secrets.ENVIRONMENT }}/ubuntu.env
                - env/base/kubernetes.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes.env
                - env/base/kubernetes_1_25.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes_1_25.env
                - vars/base/common.json
                - vars/${{ secrets.ENVIRONMENT }}/common.json
                - vars/base/kvm.json
                - vars/${{ secrets.ENVIRONMENT }}/kvm.json
                - vars/base/linux.json
                - vars/${{ secrets.ENVIRONMENT }}/linux.json
                - vars/base/ubuntu.json
                - vars/${{ secrets.ENVIRONMENT }}/ubuntu.json
                - vars/base/kubernetes.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes.json
                - vars/base/kubernetes_1_25.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes_1_25.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
          - name: kubernetes-1-26
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_26
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/base/common.env
                - env/${{ secrets.ENVIRONMENT }}/common.env
                - env/base/kvm.env
                - env/${{ secrets.ENVIRONMENT }}/kvm.env
                - env/base/linux.env
                - env/${{ secrets.ENVIRONMENT }}/linux.env
                - env/base/ubuntu.env
                - env/${{ secrets.ENVIRONMENT }}/ubuntu.env
                - env/base/kubernetes.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes.env
                - env/base/kubernetes_1_26.env
                - env/${{ secrets.ENVIRONMENT }}/kubernetes_1_26.env
                - vars/base/common.json
                - vars/${{ secrets.ENVIRONMENT }}/common.json
                - vars/base/kvm.json
                - vars/${{ secrets.ENVIRONMENT }}/kvm.json
                - vars/base/linux.json
                - vars/${{ secrets.ENVIRONMENT }}/linux.json
                - vars/base/ubuntu.json
                - vars/${{ secrets.ENVIRONMENT }}/ubuntu.json
                - vars/base/kubernetes.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes.json
                - vars/base/kubernetes_1_26.json
                - vars/${{ secrets.ENVIRONMENT }}/kubernetes_1_26.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
    name: ${{ matrix.name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check if image should be built
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: ${{ matrix.path-filters }}

      - name: Set up Packer environment
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: ./bin/setup

      - name: Write OpenStack credentials
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: echo "$CLOUDS_YAML_B64" | base64 -d > ./clouds.yaml
        env:
          CLOUDS_YAML_B64: ${{ secrets.CLOUDS_YAML_B64 }}

      - name: Build image
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: ./bin/build
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          PACKER_TEMPLATE: ${{ matrix.template }}
          ENV_VAR_FILES: ${{ matrix.var-files }}

      - name: Publish image to prerelease bucket
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: ./bin/publish
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          ENV_VAR_FILES: ${{ matrix.var-files }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
