name: Build images
on:
  push:
    branches: [main]
jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - name: ubuntu-desktop
          #   template: linux-desktop
          #   var-files: common,linux,ubuntu
          - name: ubuntu-webconsole
            template: linux-webconsole
            var-files: common,linux,ubuntu
          - name: jupyter-repo2docker
            template: jupyter-repo2docker
            var-files: common,linux,ubuntu
    name: ${{ matrix.name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Packer environment
        run: ./bin/setup

      - name: Write OpenStack credentials
        run: echo "$CLOUDS_YAML_B64" | base64 -d > ./clouds.yaml
        env:
          CLOUDS_YAML_B64: ${{ secrets.CLOUDS_YAML_B64 }}

      - name: Build image
        run: ./bin/build
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          PACKER_TEMPLATE: ${{ matrix.template }}
          ENV_VAR_FILES: ${{ matrix.var-files }}

      - name: Publish image to prerelease bucket
        run: ./bin/publish
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          ENV_VAR_FILES: ${{ matrix.var-files }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
