name: Build images
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Each job consumes a FIP, so limit the number that can run concurrently
      max-parallel: 1
      matrix:
        include:
          - name: ubuntu-desktop
            template: linux-desktop
            var-files: common,kvm,linux,ubuntu
          - name: ubuntu-rdp-gateway
            template: linux-rdp-gateway
            var-files: common,kvm,linux,ubuntu
          - name: jupyter-repo2docker
            template: jupyter-repo2docker
            var-files: common,kvm,linux,ubuntu
          - name: kubernetes-1-23
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_23
          - name: kubernetes-1-24
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_24
          - name: kubernetes-1-25
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_25
          - name: kubernetes-1-26
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_26
    name: ${{ matrix.name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Packer environment
        run: ./bin/setup

      - name: Write OpenStack credentials
        run: echo "$CLOUDS_YAML_B64" | base64 -d > ./clouds.yaml
        env:
          CLOUDS_YAML_B64: ${{ secrets.CLOUDS_YAML_B64 }}

      - name: Build image
        run: ./bin/build
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          PACKER_TEMPLATE: ${{ matrix.template }}
          ENV_VAR_FILES: ${{ matrix.var-files }}

      - name: Publish image to prerelease bucket
        run: ./bin/publish
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          ENV_VAR_FILES: ${{ matrix.var-files }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
