name: Build images
on:
  push:
    branches: [main]
jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Each job consumes a FIP, so limit the number that can run concurrently
      max-parallel: 1
      matrix:
        include:
          - name: ubuntu-desktop
            template: linux-desktop
            var-files: common,kvm,linux,ubuntu
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/*/common.env
                - env/*/kvm.env
                - env/*/linux.env
                - env/*/ubuntu.env
                - vars/*/common.json
                - vars/*/kvm.json
                - vars/*/linux.json
                - vars/*/ubuntu.json
                - packer/linux-desktop.pkr.hcl
                - ansible/linux-webconsole.yml
                - ansible/roles/linux-webconsole/**
                - ansible/roles/linux-ansible-init/**
                - ansible/roles/linux-podman/**
                - ansible/roles/linux-data-volumes/**
                - ansible/roles/linux-guacamole/**
                - ansible/roles/linux-monitoring/**
                - ansible/roles/linux-zenith-client/**
          - name: ubuntu-rdp-gateway
            template: linux-rdp-gateway
            var-files: common,kvm,linux,ubuntu
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/*/common.env
                - env/*/kvm.env
                - env/*/linux.env
                - env/*/ubuntu.env
                - vars/*/common.json
                - vars/*/kvm.json
                - vars/*/linux.json
                - vars/*/ubuntu.json
                - packer/linux-rdp-gateway.pkr.hcl
                - ansible/linux-rdp-gateway.yml
                - ansible/roles/linux-rdp-gateway/**
                - ansible/roles/linux-ansible-init/**
                - ansible/roles/linux-podman/**
                - ansible/roles/linux-data-volumes/**
                - ansible/roles/linux-guacamole/**
                - ansible/roles/linux-zenith-client/**
          - name: jupyter-repo2docker
            template: jupyter-repo2docker
            var-files: common,kvm,linux,ubuntu
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/*/common.env
                - env/*/kvm.env
                - env/*/linux.env
                - env/*/ubuntu.env
                - vars/*/common.json
                - vars/*/kvm.json
                - vars/*/linux.json
                - vars/*/ubuntu.json
                - packer/jupyter-repo2docker.pkr.hcl
                - ansible/jupyter-repo2docker.yml
                - ansible/roles/jupyter-repo2docker/**
                - ansible/roles/linux-ansible-init/**
                - ansible/roles/linux-podman/**
                - ansible/roles/linux-data-volumes/**
                - ansible/roles/linux-monitoring/**
                - ansible/roles/linux-zenith-client/**
          - name: kubernetes-1-24
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_24
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/*/common.env
                - env/*/kvm.env
                - env/*/linux.env
                - env/*/ubuntu.env
                - env/*/kubernetes.env
                - env/*/kubernetes_1_24.env
                - vars/*/common.json
                - vars/*/kvm.json
                - vars/*/linux.json
                - vars/*/ubuntu.json
                - vars/*/kubernetes.json
                - vars/*/kubernetes_1_24.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
          - name: kubernetes-1-25
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_25
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/*/common.env
                - env/*/kvm.env
                - env/*/linux.env
                - env/*/ubuntu.env
                - env/*/kubernetes.env
                - env/*/kubernetes_1_25.env
                - vars/*/common.json
                - vars/*/kvm.json
                - vars/*/linux.json
                - vars/*/ubuntu.json
                - vars/*/kubernetes.json
                - vars/*/kubernetes_1_25.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
          - name: kubernetes-1-26
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_26
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/*/common.env
                - env/*/kvm.env
                - env/*/linux.env
                - env/*/ubuntu.env
                - env/*/kubernetes.env
                - env/*/kubernetes_1_26.env
                - vars/*/common.json
                - vars/*/kvm.json
                - vars/*/linux.json
                - vars/*/ubuntu.json
                - vars/*/kubernetes.json
                - vars/*/kubernetes_1_26.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
          - name: kubernetes-1-27
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_27
            path-filters: |
              paths:
                - .github/workflows/build.yml
                - requirements.yml
                - env/*/common.env
                - env/*/kvm.env
                - env/*/linux.env
                - env/*/ubuntu.env
                - env/*/kubernetes.env
                - env/*/kubernetes_1_27.env
                - vars/*/common.json
                - vars/*/kvm.json
                - vars/*/linux.json
                - vars/*/ubuntu.json
                - vars/*/kubernetes.json
                - vars/*/kubernetes_1_27.json
                - packer/kubernetes.pkr.hcl
                - vendor/image-builder/**
    name: ${{ matrix.name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check if image should be built
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: ${{ matrix.path-filters }}

      - name: Set up Packer environment
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: ./bin/setup

      - name: Write OpenStack credentials
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: echo "$CLOUDS_YAML_B64" | base64 -d > ./clouds.yaml
        env:
          CLOUDS_YAML_B64: ${{ secrets.CLOUDS_YAML_B64 }}

      - name: Build image
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: ./bin/build
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          PACKER_TEMPLATE: ${{ matrix.template }}
          ENV_VAR_FILES: ${{ matrix.var-files }}

      - name: Publish image to prerelease bucket
        if: ${{ steps.changes.outputs.paths == 'true' }}
        run: ./bin/publish
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          ENV_VAR_FILES: ${{ matrix.var-files }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
