name: Build and test main

on:
  push:
    branches:
      - main

jobs:
  # Build, publish and test the images
  build_test_images:
    uses: ./.github/workflows/build_test_images.yaml
    secrets: inherit
