name: Build and publish images for tag
on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  build_images:
    runs-on: ubuntu-latest
    outputs:
      image-id: ${{ steps.build-image.outputs.image-id }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu-desktop
            template: linux-desktop
            var-files: common,kvm,linux,ubuntu-focal
          - name: ubuntu-rdp-gateway
            # template: linux-rdp-gateway
            template: linux-desktop
            var-files: common,kvm,linux,ubuntu-focal
          # - name: jupyter-repo2docker
          #   template: jupyter-repo2docker
          #   var-files: common,kvm,linux,ubuntu-focal
          # # For now, we build Kubernetes images for focal _and_ jammy
          # - name: kubernetes-1-25-focal
          #   template: kubernetes
          #   var-files: common,kvm,linux,ubuntu-focal,kubernetes,kubernetes_1_25
          # - name: kubernetes-1-25-jammy
          #   template: kubernetes
          #   var-files: common,kvm,linux,ubuntu-jammy,kubernetes,kubernetes_1_25
          # - name: kubernetes-1-26-focal
          #   template: kubernetes
          #   var-files: common,kvm,linux,ubuntu-focal,kubernetes,kubernetes_1_26
          # - name: kubernetes-1-26-jammy
          #   template: kubernetes
          #   var-files: common,kvm,linux,ubuntu-jammy,kubernetes,kubernetes_1_26
          # - name: kubernetes-1-27-focal
          #   template: kubernetes
          #   var-files: common,kvm,linux,ubuntu-focal,kubernetes,kubernetes_1_27
          # - name: kubernetes-1-27-jammy
          #   template: kubernetes
          #   var-files: common,kvm,linux,ubuntu-jammy,kubernetes,kubernetes_1_27
    name: ${{ matrix.name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Write OpenStack credentials
        run: echo "$CLOUDS_YAML_B64" | base64 -d > ./clouds.yaml
        env:
          CLOUDS_YAML_B64: ${{ secrets.CLOUDS_YAML_B64 }}

      - name: Set up Packer environment
        run: ./bin/setup

      - name: Build image
        id: build-image
        run: ./bin/build-image
        env:
          OS_CLOUD: openstack
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: arcus
          PACKER_TEMPLATE: ${{ matrix.template }}
          ENV_VAR_FILES: ${{ matrix.var-files }}

      - name: Publish image
        id: publish-image
        run: ./bin/publish-image ${{ steps.build-image.outputs.image-id }}
        env:
          OS_CLOUD: openstack
          ENVIRONMENT: arcus
          ENV_VAR_FILES: ${{ matrix.var-files }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}

      - name: Write matrix outputs
        uses: cloudposse/github-action-matrix-outputs-write@main
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.name }}
          outputs: |-
            image-id: ${{ steps.build-image.outputs.image-id }}
            image-name: ${{ steps.publish-image.outputs.image-name }}
            image-url: ${{ steps.publish-image.outputs.image-url }}
            image-checksum: ${{ steps.publish-image.outputs.image-checksum }}

  publish_manifest:
    needs: [build_images]
    runs-on: ubuntu-latest
    steps:
      - name: Read matrix outputs
        id: matrix-outputs
        uses: cloudposse/github-action-matrix-outputs-read@main
        with:
          matrix-step-name: build_images

      - name: Write outputs
        uses: DamianReeves/write-file-action@master
        with:
          path: outputs.json
          write-mode: overwrite
          contents: ${{ steps.matrix-outputs.outputs.result }}
      
      - name: Cat outputs
        run: cat outputs.json
        
    

  # TODO(mkjpryor)
  # Upload release artefact
