name: Build and publish images for tag
on:
  push:
    tags:
      - "**"

jobs:
  build_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Each job consumes a FIP, so limit the number that can run concurrently
      max-parallel: 1
      # We only build images whose dependencies have changed
      matrix:
        include:
          - name: ubuntu-desktop
            template: linux-desktop
            var-files: common,kvm,linux,ubuntu
          - name: ubuntu-rdp-gateway
            template: linux-rdp-gateway
            var-files: common,kvm,linux,ubuntu
          - name: jupyter-repo2docker
            template: jupyter-repo2docker
            var-files: common,kvm,linux,ubuntu
          - name: kubernetes-1-25
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_25
          - name: kubernetes-1-26
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_26
          - name: kubernetes-1-27
            template: kubernetes
            var-files: common,kvm,linux,ubuntu,kubernetes,kubernetes_1_27
    name: ${{ matrix.name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Write OpenStack credentials
        run: echo "$CLOUDS_YAML_B64" | base64 -d > ./clouds.yaml
        env:
          CLOUDS_YAML_B64: ${{ secrets.CLOUDS_YAML_B64 }}

      - name: Build and publish image
        uses: ./.github/actions/build-image
        with:
          environment: arcus
          packer-template: ${{ matrix.template }}
          var-files: ${{ matrix.var-files }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish: yes
          s3-access-key: ${{ secrets.S3_ACCESS_KEY }}
          s3-secret-key: ${{ secrets.S3_SECRET_KEY }}

  # TODO(mkjpryor)
  # Upload release artefact
