---

- name: Ensure required system packages are installed
  ansible.builtin.apt:
    package:
      - r-base
      # Required by `deb` option in R-Studio Server install task
      - xz-utils
      # To allow non-root rstudio user to manage a python venv
      # (https://support.posit.co/hc/en-us/articles/360023654474-Installing-and-Configuring-Python-with-RStudio)
      - python3-venv
      - python3-pip
    update_cache: true
    state: present

- name: Ensure R-Studio Server is installed
  ansible.builtin.apt:
    deb: https://download2.rstudio.org/server/focal/amd64/rstudio-server-2023.06.1-524-amd64.deb
    state: present

- name: Ensure rstudio user exists
  ansible.builtin.user:
    name: rstudio
    password: "{{ 'rstudio' | password_hash('sha512', 'irrelevant') }}"

- name: Ensure auth is disabled in rstudio config file
  ansible.builtin.blockinfile:
    block: |
      auth-none=1
    path: /etc/rstudio/rserver.conf

- name: Ensure rstudio-server systemd override file is populated
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/rstudio-server.service.d/override.conf
    create: true
    block: |
      [Service]
      Environment=USER=rstudio

- name: Ensure rstudio-server service is restarted to pick up config overrides
  ansible.builtin.systemd:
    name: rstudio-server.service
    daemon_reload: true
    state: reloaded
